# Generated by Django 4.0 on 2021-08-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='examples',
            field=models.CharField(default=models.CharField(max_length=250), max_length=250),
        ),
    ]
