# Generated by Django 4.0 on 2021-08-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_examples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='examples',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
