# Generated by Django 4.0 on 2021-08-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_examples'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='_from',
            field=models.CharField(default='farmblr', max_length=250),
        ),
    ]
