# Generated by Django 4.0 on 2021-08-14 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product__from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='_from',
            new_name='fr0m',
        ),
    ]
